APExpress/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from Aufträge.admin import admin_view


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/', admin_view.urls),
    path('', include('Aufträge.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Aufträge/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.loginpage, name='login'),
    path('main/',views.main, name='main'), 
    path('help/', views.help, name='help'),
    path('logout/',views.logoutuser, name='logout'),
    path('UA10NA/', views.ua10na,name='ua10na'),
    path('UA10NA/<str:pk>', views.ua10naedit,name='ua10naedit'),
    path('UA10NAPos/<str:pk>', views.ua10na_pos,name='ua10na_pos'),
    path('UA11AA', views.ua11aa, name='ua11aa'),
    path('UA12AS', views.ua12as, name="ua12as"),
    path('Position/<str:pk>',views.position,name='position'),
    path('UA20NR', views.ua20nr,name='ua20nr'),
    path('UA21RA', views.ua21ra,name='ua21ra'),
    path('Invoice/<str:pk>', views.invoice, name='invoice'),
    path('POD/<str:pk>', views.pod, name='pod'),
]

Aufträge/models.py
from pyexpat import model
from unittest.util import _MAX_LENGTH
from django.db import models
from datetime import date
from django.contrib.auth.models import User
import time
##### Consignee 
# Create your models here.


class Adressen(models.Model):
    id = models.AutoField(primary_key=True,unique=True,blank=False)
    firma = models.CharField(max_length=120, blank=False)
    adresse = models.CharField(max_length=200, blank=False)
    plz = models.CharField(max_length=20, blank=False)
    ort = models.CharField(max_length=100, blank=False)
    land = models.CharField(max_length=100, blank=False)
    contact = models.CharField(max_length=100, blank = True)
    phone = models.CharField(max_length=30, blank = True)
    additional = models.CharField(max_length=200, blank = True)
    date_added = models.DateTimeField(auto_now_add = True, blank = False)
    date_modified = models.DateTimeField(auto_now = True, blank = False)

    def __str__(self):
        return str(self.firma)
    
class Rechnungsempfänger(models.Model):
    id = models.AutoField(primary_key=True,unique=True,blank=False)
    firma = models.CharField(max_length=120, blank=False)
    adresse = models.CharField(max_length=200, blank=False)
    plz = models.CharField(max_length=20, blank=False)
    ort = models.CharField(max_length=100, blank=False)
    land = models.CharField(max_length=100, blank=False)
    contact = models.CharField(max_length=100, blank = True)
    phone = models.CharField(max_length=30, blank = True)
    additional = models.CharField(max_length=200, blank = True)
    date_added = models.DateTimeField(auto_now_add = True, blank = False)
    date_modified = models.DateTimeField(auto_now = True, blank = False)

    def __str__(self):
        return str(self.firma)
    

class Fahrer(models.Model):
    id = models.AutoField(primary_key=True,unique=True,blank=False)
    vorname = models.CharField(max_length=100,blank=False)
    nachname = models.CharField(max_length=100,blank=False)
    tel = models.CharField(max_length=25, blank=True)
    def __str__(self):
        return str(self.vorname)+" "+str(self.nachname)



        
class Auftrag(models.Model):
    auftragsnummer_ID = models.CharField(primary_key=True, unique=True, max_length=7, blank=True)
    auftraggeber = models.CharField(max_length=120, blank=False)
    auftragsdatum = models.DateField(blank=False, null=True)
    ausgeführt_bis = models.DateField(blank=False,null=True)
    auftragsfirma = models.ForeignKey(Adressen, on_delete=models.PROTECT, blank=False, null=True)
    auftragstext=models.TextField(blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add = True, blank = False)
    date_modified = models.DateTimeField(auto_now = True, blank = False)
    fahrer = models.ForeignKey(Fahrer,blank=False, on_delete=models.PROTECT)
    angenommen = models.BooleanField(blank=True, null=True, default=False)
    auftrag_abgeschlossen = models.BooleanField(blank=True,null=True, default=False)
    def __str__(self):
        return self.auftragsnummer_ID
    

        
class Auftragspositionen(models.Model):
    auftragsnummer = models.ForeignKey(Auftrag,on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True,unique=True)
    von = models.ForeignKey(Adressen,null=True,blank=True,on_delete=models.PROTECT, related_name='von')
    nach = models.ForeignKey(Adressen, null=True,blank=True,on_delete=models.PROTECT, related_name='nach')
    kostenstelle = models.CharField(max_length=20,blank=True,null=True)
    referenz = models.TextField(blank=True,null=True)
    einzelpreis = models.FloatField(blank=True, null=True)
    mwst = models.IntegerField(blank=True,null=True)
    anzahl = models.FloatField(blank=True, null=True) 
    empfänger = models.CharField(max_length=120,blank=True, null=True)
    unterschrift = models.TextField(blank=True, null=True)
    unterschrift_datum = models.DateField(blank=True, null=True)
    position_abgeschlossen = models.BooleanField( blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add = True, blank = True, null=True)
    date_modified = models.DateTimeField(auto_now = True, blank = True, null=True)

    @property
    def gesamtpreis(self):
        gesamt = self.einzelpreis*self.anzahl
        return gesamt
    
    @property
    def total(self):
        tot = self.einzelpreis*self.anzahl + self.einzelpreis*self.anzahl/100*self.mwst
        return tot

    def __str__(self):
        return str(self.id)
    
class Rechnung(models.Model):
    auftragsnummer = models.ForeignKey(Auftrag,on_delete=models.PROTECT)
    empfänger = models.ForeignKey(Rechnungsempfänger,on_delete=models.PROTECT, blank=False)
    rechnungsnummer = models.CharField(blank=False,max_length=7)
    rechnungsdatum = models.DateField(blank=False)
    rechnungstext = models.TextField(blank=True)
    rechnungspreis = models.FloatField(blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add = True, blank = False)
    date_modified = models.DateTimeField(auto_now = True, blank = False)

    def __str__(self):
        return str(self.rechnungsnummer)


class Help(models.Model):
    frage = models.TextField(blank=False)
    antwort = models.TextField(blank=False)
    

Aufträge/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, FileResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
from datetime import date
from django.db.models import Q
from django.forms import inlineformset_factory
from django.forms import modelform_factory
from datetime import date
from django.forms import ModelForm
from django import forms
from .filters import *
import io 
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, TableStyle, Table
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import time
from django.templatetags.static import static






def loginpage(request):
  if request.user.is_authenticated:
    return redirect('main')
  else:
    if request.method == "POST":
      username = request.POST.get('username')
      password = request.POST.get('password')

      user = authenticate(request, username=username, password=password)

      if user is not None:
        login(request, user)
        return redirect('main')
      else:
        messages.info(request, 'Username or Password incorrect!')
        render(request, 'Aufträge/login.html')
    context={}
    return render(request, 'Aufträge/login.html', context)
  
@login_required(login_url='login')
def main(request):
  akt_auf = Auftrag.objects.filter(auftrag_abgeschlossen = False)
  context = {'akt_auf':akt_auf}
  return render(request, 'Aufträge/main.html', context)

def logoutuser(request):
  logout(request)
  return redirect('login')

def calc_auftragsnummer():
  try:
    auftragsnummer = Auftrag.objects.latest('auftragsnummer_ID')
  except Auftrag.DoesNotExist:
    auftragsnummer = None

  if auftragsnummer==None:
    new_auftragsnummer = "A000001"
    return new_auftragsnummer
  else:
    auftragsnummer = Auftrag.objects.latest('auftragsnummer_ID')
    str_auftragsnummer = str(auftragsnummer).replace("A","")
    new_auftragsnummer = "A" + f"{int(str_auftragsnummer)+1:06d}"
    return new_auftragsnummer
  
def calc_rechnungsnummer():
  try:
    rechnungsnummer = Rechnung.objects.latest('rechnungsnummer')
  except Rechnung.DoesNotExist:
    rechnungsnummer = None

  if rechnungsnummer==None:
    new_rechnungsnummer = "RG00001"
    return new_rechnungsnummer
  else:
    rechnungsnummer = Rechnung.objects.latest('rechnungsnummer')
    str_rechnungsnummer = str(rechnungsnummer).replace("RG","")
    new_rechnungsnummer = "RG" + f"{int(str_rechnungsnummer)+1:05d}"
    return new_rechnungsnummer

@login_required(login_url='login')
def ua10na(request):
  auftrag = calc_auftragsnummer()
  form = UA10NAForm(initial={'auftragsnummer_ID':calc_auftragsnummer(), 'auftraggeber':request.user.get_full_name(),'auftragsdatum':date.today(),'ausgeführt_bis':date.today()})
  if request.method == "POST":
    form = UA10NAForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect("/UA10NAPos/"+auftrag)
  context={'form':form}
  return render(request, 'Aufträge/UA10NA.html',context)

@login_required(login_url='login')
def ua10naedit(request,pk):
  auftrag = Auftrag.objects.get(auftragsnummer_ID=pk)
  form = UA10NAForm(request.POST or None, instance=auftrag)
  context={'auftrag':auftrag,'form':form}
  if form.is_valid():
    form.save()
    return redirect("/")
  return render(request, 'Aufträge/UA10NA.html',context)

@login_required(login_url='login')
def ua10na_pos(request,pk):
  position = inlineformset_factory(Auftrag,Auftragspositionen,fields=['id','von','nach','referenz','kostenstelle'],extra=12,widgets={'id':forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),'von':forms.Select(attrs={'class':'form-select'}),'nach':forms.Select(attrs={'class':'form-select'}),'kostenstelle':forms.TextInput(attrs={'class':'form-control'}),'referenz':forms.Textarea(attrs={'class':'form-control','rows':1})})
  auftrag = Auftrag.objects.get(auftragsnummer_ID=pk)
  formset = position(instance=auftrag)
  if request.method == "POST":
    formset = position(request.POST, instance=auftrag)
    if formset.is_valid():
      formset.save()
      return redirect("/main")
  context={'formset':formset}
  return render(request,'Aufträge/UA10NAPos.html',context)
  

@login_required(login_url='login')
def ua11aa(request):
  all_auf = Auftrag.objects.order_by('-auftragsnummer_ID')
  context = {'all_auf':all_auf}
  return render(request, 'Aufträge/UA11AA.html', context)

@login_required(login_url='login')
def ua12as(request):
  all_pos = Auftragspositionen.objects.order_by('-auftragsnummer')
  myFilter1 = SearchPosition(request.GET,queryset=all_pos)
  all_pos = myFilter1.qs
  context = {'all_pos':all_pos, 'myFilter1':myFilter1}
  return render(request, 'Aufträge/UA12AS.html', context)

@login_required(login_url='login')
def ua20nr(request):
  form = UA20NRForm(initial={'rechnungsnummer':calc_rechnungsnummer(),'rechnungsdatum':date.today(),'rechnungstext':'Bitte überweisen Sie den ausstehenden Betrag innerhalb von 7 Tagen auf das unten genannte Konto.'})
  if request.method == "POST":
    form = UA20NRForm(request.POST)
    if form.is_valid():
      form.save()
      field = form.cleaned_data['auftragsnummer']
      a = Auftrag.objects.filter(auftragsnummer_ID=field).update(auftrag_abgeschlossen=True)
      return redirect("/")
  context={'form':form}
  return render(request,"Aufträge/UA20NR.html",context)

@login_required(login_url='login')
def ua21ra(request):
  all_rg = Rechnung.objects.order_by('-rechnungsnummer')
  all_pos = Auftragspositionen.objects.all()
  context = {'all_rg':all_rg, 'all_pos':all_pos}
  return render(request, 'Aufträge/UA21RA.html', context)

@login_required(login_url='login')
def position(request,pk):
  position = Auftragspositionen.objects.get(id=pk)
  form = Position(request.POST or None, instance=position)
  if form.is_valid():
    form.save()
    return redirect("/")
  context = {'position':position,'form': form}
  return render(request,"Aufträge/Position.html",context)


def help(request):
  hilfe = Help.objects.all()
  context = {'hilfe': hilfe}
  return render(request,'Aufträge/help.html',context)

@login_required(login_url='login')
def invoice(request,pk):
  a = Auftrag.objects.get(auftragsnummer_ID = pk)
  pos = Auftragspositionen.objects.filter(auftragsnummer=pk)
  rg = Rechnung.objects.get(auftragsnummer=pk)
  


  def generate_pdf(request):
      response = HttpResponse(content_type='application/pdf')
      response['Content-Disposition'] = 'filename="AP_Rechnung"' + rg.rechnungsnummer + "_" + str(rg.rechnungsdatum) + ".pdf"

      doc = SimpleDocTemplate(response, pagesize=A4,rightMargin=2*cm, leftMargin=2*cm, topMargin=1*cm, bottomMargin=2.5*cm, title="Rechnung")
      Title = 'Test'
      elements = []
      data = [['Pos', 'Beschreibung','Anzahl', 'Preis [€]', 'MwSt. [%]', 'Total [€]','Referenz']]
      invoice_data = []
      total_price = 0
      mw=0
      styles1 = getSampleStyleSheet()
      style1 = styles1["Normal"]
      style1.fontSize = 10
      style1.alignment = 1
      styles3 = getSampleStyleSheet()
      style3 = styles1["Normal"]
      style3.fontSize = 8
      style3.alignment = 1
      #Creating data for table
      for i in range(len(pos.values('id'))):
        v = Adressen.objects.get(id = pos.values('von')[i]['von'])
        n = Adressen.objects.get(id = pos.values('nach')[i]['nach'])
        invoice_data += [{'pos': i+1, 'beschreibung': 'Transport' + '\n' + 'Von: ' + v.firma + '\n' + 'Nach: ' + n.firma + '\n' + 'Kostenstelle: ' + pos.values('kostenstelle')[i]['kostenstelle'],'anzahl': pos.values('anzahl')[i]['anzahl'],'preis': float(format(pos.values('einzelpreis')[i]['einzelpreis'],".2f")), 'mwst': pos.values('mwst')[i]['mwst'], 'total': round(pos.values('anzahl')[i]['anzahl']*pos.values('einzelpreis')[i]['einzelpreis']+pos.values('anzahl')[i]['anzahl']*pos.values('einzelpreis')[i]['einzelpreis']/100*round(pos.values('mwst')[i]['mwst'],2),2),'referenz':pos.values('referenz')[i]['referenz']}]
        total_price += invoice_data[i]['total']
        mw = mw + round(invoice_data[i]['preis']*invoice_data[i]['anzahl']/100*invoice_data[i]['mwst'],2)
      for item in invoice_data:
          data.append([item['pos'], item['beschreibung'],int(item['anzahl']), item['preis'], item['mwst'], item['total'],Paragraph(item['referenz'],style1)])

      #Build the table 
      t=Table(data,colWidths=[0.8*cm,6.5*cm,1.1*cm,2.4*cm,1.8*cm,2*cm,3*cm])
      t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.lightgrey),
                            ('TEXTCOLOR',(0,0),(-1,0),colors.black),
                            ('ALIGN',(0,0),(-1,-1),'CENTER'),
                            ('ALIGN',(1,1),(1,-1),'LEFT'),
                            ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
                            ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
                            ('FONTSIZE',(0,0),(-1,-1),8),
                            ('BOTTOMPADDING',(0,0),(-1,0),0),
                            ('BACKGROUND',(0,1),(-1,-1),colors.beige),
                            ('GRID',(0,0),(-1,-1),1,colors.black)]))
      

      rtext = Paragraph(rg.rechnungstext)
      im = Image('/var/task/staticfiles_build/static/LogoAP.jpg',4*cm,2*cm,hAlign='RIGHT')
      def myFirstPage(canvas, doc):
        #Draws the invoice header
        canvas.setStrokeColorRGB(0.13, 0.25, 0.27)
        canvas.setFillColorRGB(0.2, 0.2, 0.2)
        canvas.setFont('Helvetica-Bold', 16)
        canvas.drawString(1.7 * cm, 19 * cm, 'Rechnung')
        canvas.setFont('Helvetica', 6)

Aufträge/templates/Aufträge/UA10NA.html
{% extends 'Aufträge/navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>APExpress</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <style>
            body{
                font-family: Roboto;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


        <div style="margin-top: 2rem; display: flex;justify-content: center;">
            <h2>Neuer Auftrag</h2>
        </div>
        <div class="container-fluid" style="width:50%;margin-top: 2rem;">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button style="display:flex;" class="btn btn-secondary mx-auto" type="submit">Submit</button>
            </form>
        </div>
    </body>
</html>
{% endblock %}

Aufträge/templates/Aufträge/UA10NAPos.html
{% extends 'Aufträge/navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>APExpress</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <style>
            body{
                font-family: Roboto;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


        <div style="margin-top: 2rem; display: flex;justify-content: center;">
            <h2>Auftragspositionen hinzufügen</h2>
        </div>
        <div class="container-fluid" style="width:100%;margin-top: 2rem;">
            <form action="" method="POST";>
                {% csrf_token %}
                {{formset.management_form}}
                <div >
                <table class="table table-striped">
                    <tr>    
                        <th>ID</th>
                        <th>Von</th>
                        <th>Nach</th>
                        <th>Kostenstelle</th>
                        <th>Referenz</th>
                    </tr>
                    {% for p in formset %}
                    <tr>
                        <td>{{p.id}}</td>
                        <td>{{p.von}}</td>
                        <td>{{p.nach}}</td>
                        <td>{{p.kostenstelle}}</td>
                        <td>{{p.referenz}}</td>
                    </tr>
                    {% endfor %}
                    
                </table>
            </div>
                <button style="display:flex;" class="btn btn-secondary mx-auto" type="submit">Submit</button>          
            </form>
        </div>

    </body>
</html>
{% endblock %}

Aufträge/templates/Aufträge/UA11AA.html
{% extends 'Aufträge/navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>APExpress</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <style>
            body{
                font-family: Roboto;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


        <div style="margin-top: 2rem; display: flex;justify-content: center;">
            <h2>Alle Aufträge</h2>
        </div>
        {% for i in all_auf %}
        <div class="accordion" id="accordionExample" style="margin-top: 2rem">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#{{i.auftragsnummer_ID}}" aria-expanded="true" aria-controls="collapseOne">
                    Auftrag {{i.auftragsnummer_ID}} von {{i.auftraggeber}} am {{i.auftragsdatum}} (ausgeführt bis spätestens: {{i.ausgeführt_bis}})
                </button>
              </h2>
              <div id="{{i.auftragsnummer_ID}}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {% if i.angenommen == True %}
                        Angenommen: <strong style="color:rgb(20, 181, 76);">Ja</strong>
                    {% else %}
                        Angenommen: <strong style="color:rgb(185, 10, 30);">Nein</strong>
                    {% endif %}<br> 
                    Fahrer: {{i.fahrer.vorname}} {{i.fahrer.nachname}}<br>
                    {% if i.auftrag_abgeschlossen == True %}
                        Rechnung geschrieben: <strong style="color:rgb(20, 181, 76);">Ja</strong>
                    {% else %}
                        Rechnung geschrieben: <strong style="color:rgb(185, 10, 30);">Nein</strong>
                    {% endif %}<br>
                    <a href="{% url 'ua10naedit' i.auftragsnummer_ID %}">{{i.auftragsnummer_ID}}</a><br>
                    <a href="{% url 'ua10na_pos' i.auftragsnummer_ID %}">Positionen ändern</a><br>
                    <a href="{% url 'pod' i.auftragsnummer_ID %}">Abliefernachweis</a><br>
                    <div >
                        <table class="table table-striped">
                            <tr>
                                <th>#</th>
                                <th>Von</th>
                                <th>Nach</th>
                                <th>Referenz</th>
                                <th>Abgeschl.</th>
                            </tr>
                            {% for j in i.auftragspositionen_set.all %}
                            <tr>
                                <td><a href="{% url 'position' j.id %}">{{j.id}}</a></td>
                                <td>{{j.von.firma}}</td>
                                <td>{{j.nach.firma}}</td>
                                <td>{{j.referenz}}</td>
                                <td>
                                {% if j.position_abgeschlossen == True %}
                                    <strong style="color:rgb(20, 181, 76);">Ja</strong>
                                {% else %}
                                    <strong style="color:rgb(185, 10, 30);">Nein</strong>
                                {% endif %}<br> 
                                </td>
                            </tr>

                            {% endfor %}
                        </table>
                    </div>
                </div>
              </div>
            </div>

        {% empty %}
        <div style="margin-top: 4rem; border-radius: 5px; display: flex; justify-content: center">
            <h5>Es gibt aktuell keine Aufträge...</h5>
        </div>
        {% endfor %}
    </body>
</html>
{% endblock %}

Aufträge/templates/Aufträge/UA20NR.html
{% extends 'Aufträge/navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>APExpress</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <style>
            body{
                font-family: Roboto;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


        <div style="margin-top: 2rem; display: flex;justify-content: center;">
            <h2>Neue Rechnung</h2>
        </div>
        <div class="container-fluid" style="width:50%;margin-top: 2rem;">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button style="display:flex;" class="btn btn-secondary mx-auto" type="submit">Submit</button>
            </form>
        </div>
    </body>
</html>
{% endblock %}

Aufträge/templates/Aufträge/main.html
{% extends 'Aufträge/navbar.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>APExpress</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
        <style>
            body{
                font-family: Roboto;
            }
        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


        <div style="margin-top: 2rem; display: flex;justify-content: center;">
            <h2>Aktuelle Aufträge</h2>
        </div>
        {% for i in akt_auf %}
        <div class="accordion" id="accordionExample" style="margin-top: 2rem">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#{{i.auftragsnummer_ID}}" aria-expanded="true" aria-controls="collapseOne">
                    Auftrag {{i.auftragsnummer_ID}} von {{i.auftraggeber}} am {{i.auftragsdatum}} (ausgeführt bis spätestens: {{i.ausgeführt_bis}})
                </button>
              </h2>
              <div id="{{i.auftragsnummer_ID}}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    {% if i.angenommen == True %}
                        Angenommen: <strong style="color:rgb(20, 181, 76);">Ja</strong>
                    {% else %}
                        Angenommen: <strong style="color:rgb(185, 10, 30);">Nein</strong>
                    {% endif %}<br> 
                    Fahrer: {{i.fahrer.vorname}} {{i.fahrer.nachname}}<br>
                    <a href="{% url 'ua10naedit' i.auftragsnummer_ID %}">{{i.auftragsnummer_ID}}</a>
                    <div >
                        <table class="table table-striped">
                            <tr>
                                <th>#</th>
                                <th>Von</th>
                                <th>Nach</th>
                                <th>Referenz</th>
                                <th>Abgeschl.</th>
                            </tr>
                            {% for j in i.auftragspositionen_set.all %}
                            <tr>
                                <td><a href="{% url 'position' j.id %}">{{j.id}}</a></td>
                                <td>{{j.von.firma}}</td>
                                <td>{{j.nach.firma}}</td>
                                <td>{{j.referenz}}</td>
                                <td>
                                {% if j.position_abgeschlossen == True %}
                                    <strong style="color:rgb(20, 181, 76);">Ja</strong>
                                {% else %}
                                    <strong style="color:rgb(185, 10, 30);">Nein</strong>
                                {% endif %}<br> 
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
              </div>
            </div>

        {% empty %}
        <div style="margin-top: 4rem; border-radius: 5px; display: flex; justify-content: center">
            <h5>Es gibt aktuell keine Aufträge...</h5>
        </div>
        {% endfor %}




    </body>

</html>
{% endblock %}